name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #날짜 및 시간 포맷팅
  intl: ^0.19.0
  #아이콘
  cupertino_icons: ^1.0.6
  # 권한 요청
  permission_handler: ^10.0.0
  #녹음
  flutter_sound: ^9.10.4
  #해당경로 저장
  path_provider: ^2.0.2
  # 구글 로그인
  google_sign_in: ^6.2.1
  #내부 디스크에 저장
  shared_preferences: ^2.1.0
  
  http: ^1.2.1
  #스톱워치 
  stop_watch_timer: ^1.3.1
  #TTS라이브러리
  flutter_tts: ^4.0.2
  #이미지 피커
  image_picker: ^1.1.2
  #무한 스크롤
  infinite_scroll_pagination: ^4.0.0
  #파일 다운로드
  flutter_downloader: ^1.11.8
  #세션 저장소
  flutter_secure_storage: ^9.2.2
  #카메라
  camera: ^0.11.0+2
  #스플래시 스크린
  flutter_native_splash: ^2.4.1

dependency_overrides:
  js: ^0.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color : "#42a5f5"

flutter:
  uses-material-design: true
  assets:
  - assets/txt_file1.txt
  - assets/images/
  - assets/images/SendManLogo.png
  - assets/images/GoogleLoginLogo.jpg
  - assets/images/GoogleLoginLogo.png
  - assets/images/InitLogo.png
  - assets/images/ExampleLogo.png
